### PR TITLE
Task-54251: update saveTransactionDetail when using metamask

### PR DESCRIPTION
**Pull request by MayTekayaa**
Adapt saveTransactionDetails function to use metamask wallet by avoiding transaction hash verification

### CODE REVIEW

**Review by ahamdi — COMMENTED** [review]
We should not save a transaction with an empty Hash. why is this needed ?

**Comment by MayTekayaa** [comment]
if the user is connected with wallet meeds, there is a rawTransaction for hash generation, otherwise if he is connected with metamask there is a hash and not a rawTransaction so i think it's useless the hash vérification

**Comment by ahamdi** [comment]
@MayTekayaa the hash is like the identifier of each transaction, it is required field

**Comment by MayTekayaa** [comment]
No need to delete the hash verification bloc

**Pull request closed without merging**
